### ISSUE TITLE
Question about the PR2 analysis

### ISSUE THREAD

**Issue by Zjianglin** [AliYoussef96/vhcub#1]
Hi @AliYoussef96 , I'm interested in `Parity rule 2 (PR2) plot`. As you mentioned in the description of the function, The Parity rule 2 (PR2) plot analysis was used to identify the effects of natural selection and mutation on codon usage bias,
which is characterized by the value of AT-bias [A3/(A3 C T3)] as the ordinate and GC-bias [G3/(G3 CC3)] as the abscissa (Sueoka,
1995). A3; T3; G3 and C3 correspond to the A, T, G, and C content at the third position of *four-codon amino acids*, respectively. The four-codon amino acids include `Ala, Arg, Gly, Leu, Pro, Ser, Thr, and Val`. However, I look at your source code of  `PR2.plot` function but found no filter or selection operation to only keep these 8 four-fold codons. How can I understand your process? or does the `PR2.plot` function need `fasta` sequences inputs that just only include these four-fold codons? Thank you.

**Comment by AliYoussef96** [comment]
Hi @Zjianglin, Yes for this version of the package you have to make the filtration step before using the PR2.plot function.

I updated the function on GitHub, the filtration step is now implemented in the function and it is ready to be used on the fasta file without the need for a pre-filtration step. 

https://github.com/AliYoussef96/vhcub/blob/1630dda448403e98481ce02ee028f17a7c69ea54/R/PR2.plot.R#L31

I will update the full package on CRAN soon with new and optimized functions.

Thank you for using our package.

**Comment by Zjianglin** [comment]
okay, thanks for your timely reply.
